/*
FILENAME: ANB Submit Details
CREATED BY: Bill Trombley
LAST UPDATED:
CHANGES MADE:
*/

SELECT T1.SUBMITDATE
,T3.IsHoliday
,T3.IsWeekday
    , TOTAL
    , MMFA
    , TOTAL - MMFA AS MMSD
FROM
(
SELECT COUNT(T1.HOLDINGKEY) AS TOTAL
    , T2.APP_COUNT AS MMFA
    , CAST(NEWBUSINESSSUBMITDATE AS DATE) AS SUBMITDATE
FROM PROD_DMA_VW.ANB_APPLICATION_RPT_VW T1
INNER JOIN (SELECT COUNT(OREPLACE(T1.ORDERENTRYID,'-','')) AS APP_COUNT
                            , CAST(T1.SUITCOMPLETEDATETRANSMITTED AS DATE) AS SUBMITDATE
                        FROM PROD_DMA_VW.IPIPELINE_ORDERS_VW T1
                        WHERE PRODUCTNAME LIKE 'MassMutual%'
                        GROUP BY 2) T2 ON CAST(T1.NEWBUSINESSSUBMITDATE AS DATE) = T2.SUBMITDATE
GROUP BY 2,3) T1

LEFT JOIN 
	PROD_DMA_VW.Date_DIM_VW T3 ON T3.SHORTDATE = T1.SUBMITDATE