/*  
FILENAME: VOC INTEGRATED VIEW
CREATED BY: Kristin Carlile
LAST UPDATED: 5/2/2022
CHANGES MADE: Vertica SQL Creation
 */

SELECT survey_id
, survey_number as "Survey Number"
, survey_alias as "Survey Alias"
, survey_nm as "Survey Name"
, survey_response_id as "Survey Response ID"
, survey_question_id as "Survey Question ID"
, survey_question_name as "Survey Question Name"
, survey_question_description as "Survey Question Description"
, survey_question_target as "Survey Question Target"
, survey_question_target_met as "Survey Question Target Met"
, survey_question_weight as "Survey Question Weight"
, survey_question_response as "Survey Question Response"
, survey_question_response_text as "Survey Question Response Text"
, metric_id as "Metric ID"
, metric_name as "Metric Name"
, response_date as "Response Date"
, lob_id as "LOB ID" 
, lob_name as "LOB Name"
--, work_id as "Work ID"
--, work_organization_id as "Work Organization ID"
, work_department_id as "Work Department ID"
--, function_id as "Function ID"
--, segment_id as "Segment ID"
--, work_event_id as "Work Event ID"
--, work_role_id as "Work Role ID"
--, work_system_id as "Work System ID"
, work_organization_nm as "Work Organization Name"
, department_nm as "Department Name"
, function_nm as "Function Name"
, segment_nm as "Segment Name"
, work_event_nm as "Work Event Name"
, primary_role_nm as "Primary Role Name"
, system_nm as "System Name"
, work_event_num as "Work Event Number"
, department_cd as "Department Code"
, division_cd as "Division Code"
--, tat_goal as "TAT Goal"
, prod_credit as "Prod Credit"
--, met_expected_ind as "Met Expected Ind"
--, igo_ind as "IGO Ind"
--, lead_time_ind as "Lead Time Ind"
--, custom_prod_tat_ind as "Custom Prod TAT Ind"
--, custom_prod_credit_ind as "Custom Prod Credit Ind"
--, logged_function_id as "Logged Function ID"
--, logged_segment_id as "Logged Segment ID"
--, logged_function_nm as "Logged Function Name"
--, logged_segment_nm as "Logged Segment Name"
--, demand_credit as "Demand Credit"
--, voc_ind as "VOC Ind"
--, team_party_id as "Team Party ID"
--, party_employee_id as "Party Employee ID"
, employee_organization_id as "Employee Organization ID"
, employee_team_id as "Employee Team ID"
--, party_type_id as "Party Type ID"
--, employee_role_id as "Employee Role ID"
--, site_id as "Site ID"
, employee_department_id as "Employee Department ID"
--, parent_party_id as "Parent Party ID"
--, party_type_nm as "Party Type Name"
, employee_organization_nm as "Employee Organization Name"
, employee_department_nm as "Employee Department Name"
, team_nm as "Team Name"
, role_nm as "Role Name"
, mmid as "MMID"
, employee_last_nm ||', ' || employee_first_nm as "Employee Name"
, manager_mmid as "Manager MMID"
, manager_last_nm || ', ' || manager_first_nm  as "Manager Name"
--, site_nm as "Site Name"
--, hire_dt as "Hire Date"
--, effective_dt as "Effective Date"
--, termination_dt as "Termination Date"
--, internal as "Internal"
--, hr_id as "HR ID"
--, report_ind as "Report Ind"
--, fte as "FTE"
--, ltc_ind as "LTC Ind"
--, trex_ind as "Trex Ind"
--, to_rep_ind as "to rep ind"
--, dibs_examiner_id as "DIBS Examiner ID"
--, dibs_operator_id as "DIBS Operator ID"
--, pindrop_user_id as "Pindrop User ID"
--, tpp_associate_id as "TPP Associate ID"
--, role_grade_id as "Role Grade ID"
--, role_grade_nm as "Role Grade Name"
, agent_id as "Agent ID"
, agency_id as "Agency ID"
FROM dma_vw.fact_VOC_integrated_vw