/*
* This routine pulls dma_vw.enhanced_auth_tier3_call_base_vw data
*  for use in data source Fraud Ops Call-Level Ins Ops Enhanced Auth Detail
*  Peer Review & Change Log: 
*  Peer Review Date: 5/10/2022
*  Source for this routine is dma_vw.enhanced_auth_tier3_call_base_vw
*  Author: Christina Valenti
*  Created: 5/18/2022
*  Revised:
*/
SELECT
	tier3_base_natural_key_hash_uuid,
	transmit_call_dt AS "Call Date",
	transmit_incontact_id AS "Incontact Id",
	transmit_pindrop_call_id AS "Pindrop Call Id",
	transmit_caller_role AS "Caller Role",
	transmit_line_type AS "Line Type",
	transmit_id_claim AS "Id Claim",
	transmit_auth_requested_status "Auth Requested Status",
	transmit_ivr_containment AS "IVR Containment",
	transmit_destination AS "Destination",
	transmit_iops_inputs_incoming_tfn AS "Incoming Tfn",
	transmit_iops_inputs_phone_number AS "Phone Number",
	transmit_cor_journey_count AS "Correlation Journey Count",
	transmit_ivr_journey_count AS "IVR Journey Count",
	transmit_csrtransfer_journey_count AS "CSR Journey Count",
	transmit_postivr_auth_journey_count AS "Post-IVR Auth Journey Count",
	transmit_feedback_journey_count AS "Feedback Journey Count",
	transmit_ivr_authwithacc_api_count AS "IVR Passport API Count",
	transmit_postivr_authwithacc_api_count "Post-IVR Passport API Count",
	transmit_auth_result_change AS "Auth Result Change",
	transmit_min_api_call_rec AS "Transmit Min API Call Rec",
	transmit_enhanced_auth_result AS "Enhanced Auth Result",
	transmit_voice_impact AS "Voice Impact",
	transmit_caller_status AS "Caller Status",
	transmit_call_positions AS "Call Positions",
	transmit_ea_eligible AS "EA Eligible",
	transmit_ea_ineligible_reason AS "EA Ineligible Reason",
	correlation_transmit_correlation_natural_key_hash_uuid,
	correlation_response,
	correlation_status,
	correlation_sub_journey_end,
	correlation_sub_journey_start,
	correlation_description,
	correlation_iops_inputs_alternate_id,
	correlation_transmit_api_call_rec,
	correlation_transmit_api_call_resp,
	ivr_transmit_auth_ivr_natural_key_hash_uuid,
	ivr_authwith_acc_response_body_data_acc_alias,
	ivr_authwith_acc_response_body_data_auth_reason,
	ivr_authwith_acc_response_body_data_auth_result,
	ivr_authwith_acc_response_body_data_auth_score,
	ivr_authwith_acc_response_body_data_fraud_risk_reason,
	ivr_authwith_acc_response_body_data_fraud_score,
	ivr_authwith_acc_response_status,
	ivr_description,
	ivr_ecdm_customer_combined_response_status,
	ivr_ecdm_customer_data_member_id,
	ivr_external_verification,
	ivr_iocc_auth_reason,
	ivr_iocc_auth_result,
	ivr_iops_inputs_alternate_id,
	ivr_iops_inputs_destination,
	ivr_iops_inputs_member_id,
	ivr_iops_inputs_ssn_match,
	ivr_payfone_id_result,
	ivr_payfone_id_result_trust_score_v2,
	ivr_payfone_id_result_verify_v2,
	ivr_payfone_trustscore_v2_response_trust_score,
	ivr_payfone_trustscore_v2_response_status_2,
	ivr_payfone_verify_api_response_address_address_score,
	ivr_payfone_verify_api_response_identifiers_dob,
	ivr_payfone_verify_api_response_identifiers_ssn,
	ivr_payfone_verify_api_response_name_first_name,
	ivr_payfone_verify_api_response_name_last_name,
	ivr_payfone_verify_api_response_name_name_score,
	ivr_payfone_verify_api_response_trust_score,
	ivr_payfone_verify_api_response_verified,
	ivr_payfone_verify_api_response_status_2,
	ivr_transmit_api_call_rec,
	ivr_transmit_api_call_resp,
	ivr_id_claim AS "IVR Id Claim",
	ivr_auth_requested_status AS "IVR Auth Requested Status",
	ivr_caller_status AS "IVR Caller Status",
	ivr_enhanced_auth_result AS "IVR Enhanced Auth Result",
	ivr_voice_auth_result AS "IVR Voice Auth Result",
	csr_transmit_csrtransfer_natural_key_hash_uuid,
	csr_trans_status,
	csr_description,
	csr_iops_inputs_alternate_id,
	csr_iops_inputs_destination,
	csr_iops_inputs_member_id,
	csr_iops_inputs_ssn_match,
	csr_transmit_api_call_rec,
	csr_transmit_api_call_resp,
	postivr_transmit_auth_postivr_natural_key_hash_uuid,
	postivr_authwith_acc_response_body_data_acc_alias,
	postivr_authwith_acc_response_body_data_auth_reason,
	postivr_authwith_acc_response_body_data_auth_result,
	postivr_authwith_acc_response_body_data_auth_score,
	postivr_authwith_acc_response_body_data_fraud_risk_reason,
	postivr_authwith_acc_response_body_data_fraud_score,
	postivr_authwith_acc_response_status,
	postivr_call_risk_api_response_body_data_risk_score,
	postivr_call_risk_api_response_status,
	postivr_description,
	postivr_ecdm_customer_combined_response_status,
	postivr_ecdm_customer_data_member_id,
	postivr_external_verification,
	postivr_iocc_auth_reason,
	postivr_iocc_auth_result,
	postivr_iops_inputs_alternate_id,
	postivr_iops_inputs_case_id,
	postivr_iops_inputs_destination,
	postivr_iops_inputs_member_id,
	postivr_iops_inputs_ssn_match,
	postivr_payfone_id_result,
	postivr_payfone_id_result_trust_score_v2,
	postivr_payfone_id_result_verify_v2,
	postivr_payfone_trustscore_v2_response_trust_score,
	postivr_payfone_trustscore_v2_response_status_2,
	postivr_payfone_verify_api_response_address_address_score,
	postivr_payfone_verify_api_response_identifiers_dob,
	postivr_payfone_verify_api_response_identifiers_ssn,
	postivr_payfone_verify_api_response_name_first_name,
	postivr_payfone_verify_api_response_name_last_name,
	postivr_payfone_verify_api_response_name_name_score,
	postivr_payfone_verify_api_response_trust_score,
	postivr_payfone_verify_api_response_verified,
	postivr_payfone_verify_api_response_status_2,
	postivr_transmit_api_call_rec,
	postivr_transmit_api_call_resp,
	postivr_transmit_api_response_time,
	postivr_auth_type AS "Post-IVR Auth Type",
	postivr_id_claim AS "Post-IVR Id Claim",
	postivr_auth_requested_status AS "Post-IVR Auth Requested Status",
	postivr_caller_status AS "Post-IVR Caller Status",
	postivr_enhanced_auth_result AS "Post-IVR Enhanced Auth Result",
	postivr_voice_auth_result AS "Post-IVR Voice Auth Result",
	fb_transmit_feedback_natural_key_hash_uuid,
	fb_call_risk_api_response_body_data_risk_score,
	fb_call_risk_api_response_status,
	fb_description,
	fb_external_verification,
	fb_feedback_api_response_status,
	fb_iops_inputs_alternate_id,
	fb_iops_inputs_case_id,
	fb_iops_inputs_destination,
	fb_iops_inputs_kba_result,
	fb_iops_inputs_m_auth,
	fb_iops_inputs_member_id,
	fb_iops_inputs_otp_language,
	fb_iops_inputs_otp_result,
	fb_iops_inputs_otv_result,
	fb_iops_inputs_ssn_match,
	fb_transmit_api_call_rec,
	fb_transmit_api_call_resp,
	fb_transmit_api_response_time,
	fb_case_id_count,
	fb_csr_feedback_third_party_ind AS "Feedback Third Party Indicator",
	passport_phone_num,
	passport_call_start_dtm,
	passport_ivr_start_dtm,
	passport_agent_start_dtm,
	passport_call_end_dtm,
	passport_duration,
	passport_pindrop_call_id,
	passport_correlation_alt_id,
	passport_destination_phone_num,
	passport_lob,
	passport_account,
	passport_device_type,
	passport_carrier,
	passport_location,
	passport_caller_id_blacklisted,
	passport_caller_id_whitelisted,
	passport_risk_result,
	passport_auth_result,
	passport_auth_policy,
	passport_enrollment_pol,
	passport_caller_id_validated,
	passport_auth_feedback,
	passport_auth_score,
	passport_behavior_score,
	passport_device_score,
	passport_voice_score,
	passport_risk_score,
	passport_device_risk,
	passport_behavior_risk,
	passport_voice_risk,
	passport_caller_status AS "Passport Caller Status", 
	passport_auth_status AS "Passport Auth Status",
	passport_new_enrollment AS "Passport New Enrollment",
	row_process_dtm
FROM
	dma_vw.enhanced_auth_tier3_call_base_vw