/*
FILENAME: ANB CURRENT PENDING INVENTORY
CREATED BY: Jess Madru
LAST UPDATED: 10/15/2021
CHANGES MADE: 
*/

SELECT T1.RWOBNUM  AS SourceTransactionID
	, T1.CONTRACTNUMBER AS "Contract"
	, T1.PESSPOLICYPREFFIX AS "Contract Prefix"
	, T1.CONTROLID AS OrderEntryID
	, CAST(T1.RCREATEDATE AS DATE) AS "Received Date"
	, CAST(T1.RSTATUSTIME AS DATE) AS "Trans Date"
	, CAST(T1.TPENDTIME AS DATE) AS "Pend Date"
	, T1.WORKTYPE AS "Work Type"
	, T1.TRANSACTIONTYPE AS "Transaction Type"
	, T1.DOCUMENTTYPE AS "Document Type"
	, T3.FUNCTIONNAME AS "Function"
	, T3.SEGMENTNAME AS "Segment"
	, T3.WORKEVENTID AS WorkEventID
	, T3.TATGOAL AS "TAT Goal"
	, T1.TSTEPNAME AS "Work Status"
	, CAST(CURRENT_DATE AS DATE) - CAST(T1.RSTATUSTIME AS DATE) AS "Trans Days Pending"
	, CAST(CURRENT_DATE AS DATE) - CAST(T1.RCREATEDATE AS DATE) AS "Days Pending"
	, CAST(CURRENT_DATE AS DATE) - CAST(T1.TPENDTIME AS DATE) AS "Pend Days Pending"
        , UPPER(T1.ASSIGNEDTO) AS AssignedToMMID
	, T2.ORGANIZATIONNAME AS "Organization"
	, T2.DEPARTMENTNAME AS "Department"
	, TeamName AS "Team"
	, EmployeeLastName||', '||EmployeeFirstName AS "Employee"
	, RoleName AS "Role"
	, ManagerLastName||', '||ManagerFirstName AS "Manager"
	, T1.PRODUCEID AS AgentID
	, T1.AGENCY AS Firm
	, T1.PRODUCT AS "Product Name"
	, T1.CONTRACTSTATE AS "Contract State"
FROM PROD_DMA_VW.ANB_WORK_OBJECT_VW T1
LEFT JOIN PROD_DMA_VW.EMPLOYEE_PIT_DIM_VW T2 ON UPPER(T1.ASSIGNEDTO) = T2.MMID AND T1.RCREATEDATE BETWEEN T2.STARTDATE AND T2.ENDDATE
LEFT JOIN PROD_DMA_VW.WORK_EVENT_CURR_DIM_VW T3 ON T3.WORKEVENTNAME = T1.WORKTYPE

WHERE T1.TSTEPNAME IN ('ACTIVE','PEND','NEW')
	AND T1.WORKTYPE <> ''