SELECT  [Policy Number]
      ,[Admin System]
      ,[Payment Frequency]
      ,[DRAFT_DAY]
      ,[PLAN_STRT_DTE]
      ,[PLAN_END_DTE]
      ,[PRINCIPAL_APPLIED]
      ,[ORIG_LOAN_AMT]
      ,[STATUS_CDE] AS "Status Code"
      ,[ADMN_SYS_CDE2]
      ,[SEC_CDE]
      ,[Customer Age]
      ,[Issue Date of Policy]
      ,[PD_TO_DATE]
      ,[Major Product Type]
      ,[Line of Business]
      ,[Product Type]
      ,[Contract State]
      ,[Resident State]
      ,[FK_SVCCHNL_SRC_CDE]
      ,[Service Channel Name]
      ,[CPLT_IND] AS "Completed Indicator"
      ,[CREATE_DTE] AS "Create Date"
      ,[Face Amount]
  FROM [RptgAndAnalytics].[Adhoc].[Repayment_Data_COVID]