SELECT [Policy Number]
      ,[HLDG_STUS]
      ,[Admin System]
      ,[CATS Logged Date]
      ,[Frequency?]
      ,[Issue Date of Policy]
      ,[PD_TO_DATE]
      ,[Major Product Type]
      ,[Line of Business]
      ,[Product Type]
      ,[Contract State]
      ,[FK_SVCCHNL_SRC_CDE]
      ,[Service Channel Name]
      ,[CPLT_IND]
      ,[Face Amount]
      ,[POL_NUM]
      ,[ADMN_SYS_CDE]
      ,[ENROL_EXPIR_DTE]
      ,[Owner_Full_Name]
      ,[LETTER_CREATE_DTE]
      ,[Number of days since expiration]
      --,[Date Report Ran]
      ,[DPD_STATUS_CDE]
      ,[Policy Offered DPD Letter?]
      ,[Premium Amount]
      ,[Resident State]
      ,[STUS_CTGY_DESC]
  FROM [RptgAndAnalytics].[Adhoc].[Fringe_Repayment_Policies_COVID]