SELECT 
 [INCIDENT_ID]
,[INCIDENT_TYPE_ID]
,[DATA_SOURCE]
,[SERVER_TYPE]
,[IMPACT_AND_DES]
,[ACTIVE_IND]
,[LOG_DTS]
,[RESOLUTION_DTS]
,[PORTAL_ALERT_TEXT]

FROM [DMA].[dbo].[DMA_INCIDENT_EVENTS]

WHERE [LOG_DTS] >= DATEADD(dd, -365, GETDATE())