SELECT  
  T1.[WORKFLOW_NUM] AS JobNumber
, [WORKFLOW_DESC] AS JobName
, -99 AS TaskNumber
, 'N/A' AS TaskName
, [BEGIN_DTS] AS BeginDTM
, [END_DTS] AS EndDTM
, CASE WHEN [PASS_IND] = 1 THEN 'Pass' ELSE 'Fail' END AS PassFail

 

FROM [DMA].[dbo].[BSBI_WORKFLOW_RUN_LOG] T1
LEFT OUTER JOIN [DMA].[dbo].[BSBI_WORKFLOW_LOV] T2 ON T1.[WORKFLOW_NUM] = T2.[WORKFLOW_NUM]