select
source_transaction_id,
party_employee_id,
concat((employee_last_nm||', '),employee_first_nm) as employee_nm,
employee_organization_id,
organization_nm,
employee_department_id,
department_nm,
employee_role_id,
role_nm,
concat((manager_last_nm||', '),manager_first_nm) as manager_nm,
team_nm,
work_event_nm,
work_event_organization_id,
work_event_organization_nm,
work_event_department_id,
work_event_department_nm,
function_nm,
segment_nm,
insured_last_nm,
insured_first_nm,
insured_middle_nm,
pol_nr,
apm_grp_ident,
rcvd_dt,
expected_completed_dt,
cats_expected_completed_dt,
days_pending,
days_past_tat,
tat_goal,
prod_credit,
sht_cmnt_des,
chnl_dspy_nm,
admn_sys_cde,
cast(source_system_id as int) as source_system_id,
log_dt,
group_type_nm,
null as group_id,
null as major_prod_nm,
case when bcc_ind=0 then'N'
  when bcc_ind=1 then 'Y'
   end AS "Society 1851",
case when pol_nr is null and group_nm is not null then group_nm else pol_nr end as "Policy / Group #",
row_process_dtm
from dma_vw.rpt_cats_curr_pend_vw
where (employee_department_id = 2) and (function_nm <> 'Flags/Blockers' or function_nm is null)
union
select
source_transaction_id,
party_employee_id,
employee_nm,
employee_organization_id,
employee_organization_nm,
employee_department_id,
employee_department_nm,
employee_role_id,
employee_role_nm,
manager_nm,
team_nm,
work_event_nm,
work_event_organization_id,
work_event_organization_nm,
work_event_department_id,
work_event_department_nm,
function_nm,
segment_nm,
insured_last_nm  ,
insured_first_nm,
insured_middle_nm,
pol_nr,
group_num,
cast(received_dt as date) as received_dt,
cast(expected_completed_dt as date) as expected_completed_dt,
cast(source_expected_completed_dt as date) as source_expected_completed_dt,
days_pending,
days_past_tat,
tat_goal ,
prod_credit,
short_comments,pol_nr
chnl_dspy_nm,
admn_sys_cde,
cast(admn_sys_id as int) as source_system_id,
log_dt,
group_type_nm ,
group_id,
major_prod_nm,
case when bcc_ind is null  then'N'
  when bcc_ind is not null then 'Y'
   end  as "Society 1851",
case when pol_nr is null and group_num is not null then group_num else pol_nr end as "Policy / Group #",
row_process_dtm
from dma_vw.dipms_curr_pend_vw   ----curr_pend_dipms_vw was this view but has changed LC
where (employee_department_id = 2) and (function_nm <> 'Flags/Blockers' or function_nm is null)