SELECT 
'ACCESS' USAGE_TYPE
,HE.ID EVENT_ID
,HET.NAME EVENT_NAME
,HET.ACTION_TYPE
,HU.NAME MMID
,HU.EMAIL USER_EMAIL
,SU.FRIENDLY_NAME USERNAME
,HV.NAME VIEW_NAME
,HD.NAME DATA_SOURCE_NAME
,HW.NAME WORKBOOK_NAME
,HP.NAME PROJECT_NAME
,CAST(HE.CREATED_AT AS DATE) EVENT_DATE
,HE.CREATED_AT EVENT_START_DATETIME
,NULL EVENT_END_DATETIME
,0 FAIL_FLAG
,HS.NAME SITE_NAME
FROM WORKGROUP.PUBLIC.HISTORICAL_EVENTS HE
LEFT JOIN WORKGROUP.PUBLIC.HISTORICAL_EVENT_TYPES HET
ON HE.HISTORICAL_EVENT_TYPE_ID = HET.TYPE_ID
LEFT JOIN WORKGROUP.PUBLIC.HIST_DATASOURCES HD
ON HD.ID = HE.HIST_DATASOURCE_ID
LEFT JOIN WORKGROUP.PUBLIC.HIST_VIEWS HV
ON HV.ID = HE.HIST_VIEW_ID
LEFT JOIN WORKGROUP.PUBLIC.HIST_WORKBOOKS HW
ON HW.ID = HE.HIST_WORKBOOK_ID
LEFT JOIN WORKGROUP.PUBLIC.WORKBOOKS W
ON W.ID = HW.WORKBOOK_ID
LEFT JOIN WORKGROUP.PUBLIC.HIST_PROJECTS HP
ON HP.ID = HE.HIST_PROJECT_ID
LEFT JOIN WORKGROUP.PUBLIC.PROJECTS P
ON P.ID = HP.PROJECT_ID
LEFT JOIN WORKGROUP.PUBLIC.HIST_USERS HU
ON HE.HIST_ACTOR_USER_ID = HU.ID
LEFT JOIN WORKGROUP.PUBLIC.USERS U
ON U.ID = HU.USER_ID
LEFT JOIN WORKGROUP.PUBLIC.SYSTEM_USERS SU
ON SU.ID = U.SYSTEM_USER_ID
LEFT JOIN WORKGROUP.PUBLIC.HIST_SITES HS
ON HS.ID = HE.HIST_TARGET_SITE_ID
WHERE HS.SITE_ID IN (4,18)
AND HET.TYPE_ID IN (84,112)

UNION

SELECT 
USAGE_TYPE
,EVENT_ID
,EVENT_NAME
,ACTION_TYPE
,MMID
,USER_EMAIL
,USERNAME
,VIEW_NAME
,DATA_SOURCE_NAME
,COALESCE(WORKBOOK_NAME, DATA_SOURCE_NAME)
,PROJECT_NAME
,CAST(EVENT_START_DATETIME AS DATE) EVENT_DATE
,EVENT_START_DATETIME
,EVENT_END_DATETIME
,FAIL_FLAG 
,SITE_NAME
FROM
(SELECT 
'UPDATE' USAGE_TYPE
,HE.ID EVENT_ID
,HET.NAME EVENT_NAME
,HET.ACTION_TYPE
,HU.NAME MMID
,HU.EMAIL USER_EMAIL
,SU.FRIENDLY_NAME USERNAME
,HV.NAME VIEW_NAME
,CASE
	WHEN HW.NAME IS NULL THEN HD.NAME 
	ELSE HW.NAME
END DATA_SOURCE_NAME
,HW.NAME WORKBOOK_NAME
,HP.NAME PROJECT_NAME
,BJ1.STARTED_AT EVENT_START_DATETIME
,BJ1.COMPLETED_AT EVENT_END_DATETIME
,BJ1.FINISH_CODE FAIL_FLAG 
,HS.NAME SITE_NAME
FROM WORKGROUP.PUBLIC.HISTORICAL_EVENTS HE
LEFT JOIN WORKGROUP.PUBLIC.HISTORICAL_EVENT_TYPES HET
ON HE.HISTORICAL_EVENT_TYPE_ID = HET.TYPE_ID
LEFT JOIN WORKGROUP.PUBLIC.HIST_DATASOURCES HD
ON HD.ID = HE.HIST_DATASOURCE_ID
LEFT JOIN WORKGROUP.PUBLIC.HIST_VIEWS HV
ON HV.ID = HE.HIST_VIEW_ID
LEFT JOIN WORKGROUP.PUBLIC.HIST_WORKBOOKS HW
ON HW.ID = HE.HIST_WORKBOOK_ID
LEFT JOIN WORKGROUP.PUBLIC.WORKBOOKS W
ON W.ID = HW.WORKBOOK_ID
LEFT JOIN WORKGROUP.PUBLIC.HIST_PROJECTS HP
ON HP.ID = HE.HIST_PROJECT_ID
LEFT JOIN WORKGROUP.PUBLIC.PROJECTS P
ON P.ID = HP.PROJECT_ID
LEFT JOIN WORKGROUP.PUBLIC.HIST_USERS HU
ON HE.HIST_ACTOR_USER_ID = HU.ID
LEFT JOIN WORKGROUP.PUBLIC.USERS U
ON U.ID = HU.USER_ID
LEFT JOIN WORKGROUP.PUBLIC.SYSTEM_USERS SU
ON SU.ID = U.SYSTEM_USER_ID
LEFT JOIN WORKGROUP.PUBLIC.HIST_SITES HS
ON HS.ID = HE.HIST_TARGET_SITE_ID
LEFT JOIN WORKGROUP.PUBLIC.BACKGROUND_JOBS BJ1
ON SUBSTRING(BJ1.NOTES, POSITION('{' IN BJ1.NOTES) + 1, (POSITION('}' IN BJ1.NOTES) - POSITION('{' IN BJ1.NOTES))) = 
	SUBSTRING(DETAILS, POSITION('{' IN HE.DETAILS) + 1, (POSITION('}' IN HE.DETAILS) - POSITION('{' IN HE.DETAILS)))
WHERE HS.SITE_ID IN (4,18)
AND HET.TYPE_ID IN (130,131)
AND BJ1.JOB_TYPE LIKE '%refresh_extracts%'
AND SUBSTRING(BJ1.NOTES, POSITION('{' IN BJ1.NOTES) + 1, (POSITION('}' IN BJ1.NOTES) - POSITION('{' IN BJ1.NOTES))) <> '') UPDATE_SUB

UNION

SELECT 
'FAILURE' USAGE_TYPE
,BJ.ID EVENT_ID
,'Data Refresh Failure' EVENT_NAME
,BJ.JOB_NAME
,NULL
,NULL
,NULL
,BJ.TITLE VIEW_NAME
,BJ.TITLE DATA_SOURCE_NAME
,BJ.TITLE  WORKBOOK_NAME
,NULL PROJECT_NAME
,CAST(BJ.STARTED_AT AS DATE) EVENT_DATE
,BJ.STARTED_AT EVENT_START_DATETIME
,BJ.COMPLETED_AT EVENT_END_DATETIME
,BJ.FINISH_CODE FAIL_FLAG 
,HS.NAME SITE_NAME
FROM WORKGROUP.PUBLIC.BACKGROUND_JOBS BJ
LEFT JOIN WORKGROUP.PUBLIC.HIST_SITES HS
ON HS.SITE_ID = BJ.SITE_ID
WHERE HS.SITE_ID IN (4,18)
AND JOB_TYPE NOT LIKE ('%sync ad group%')
AND FINISH_CODE = 1
AND PROGRESS = 100

UNION

SELECT 
'CREATE' USAGE_TYPE
,HE.ID EVENT_ID
,HET.NAME EVENT_NAME
,HET.ACTION_TYPE
,CASE 
	WHEN HET.TYPE_ID = 3 THEN HU2.NAME
	ELSE HU.NAME 
END MMID
,CASE 
	WHEN HET.TYPE_ID = 3 THEN HU2.EMAIL 
	ELSE HU.EMAIL
END USER_EMAIL
,CASE 
	WHEN HET.TYPE_ID = 3 THEN SU2.FRIENDLY_NAME 
	ELSE SU.FRIENDLY_NAME 
END USERNAME
,HV.NAME VIEW_NAME
,HD.NAME DATA_SOURCE_NAME
,HW.NAME WORKBOOK_NAME
,HP.NAME PROJECT_NAME
,CAST(HE.CREATED_AT AS DATE) EVENT_DATE
,HE.CREATED_AT EVENT_START_DATETIME
,NULL EVENT_END_DATETIME
,0 FAIL_FLAG
,HS.NAME SITE_NAME
FROM WORKGROUP.PUBLIC.HISTORICAL_EVENTS HE
INNER JOIN WORKGROUP.PUBLIC.HISTORICAL_EVENT_TYPES HET
ON HE.HISTORICAL_EVENT_TYPE_ID = HET.TYPE_ID
LEFT JOIN WORKGROUP.PUBLIC.HIST_DATASOURCES HD
ON HD.ID = HE.HIST_DATASOURCE_ID
LEFT JOIN WORKGROUP.PUBLIC.HIST_VIEWS HV
ON HV.ID = HE.HIST_VIEW_ID
LEFT JOIN WORKGROUP.PUBLIC.HIST_WORKBOOKS HW
ON HW.ID = HE.HIST_WORKBOOK_ID
LEFT JOIN WORKGROUP.PUBLIC.WORKBOOKS W
ON W.ID = HW.WORKBOOK_ID
LEFT JOIN WORKGROUP.PUBLIC.HIST_PROJECTS HP
ON HP.ID = HE.HIST_PROJECT_ID
LEFT JOIN WORKGROUP.PUBLIC.PROJECTS P
ON P.ID = HP.PROJECT_ID
LEFT JOIN WORKGROUP.PUBLIC.HIST_USERS HU
ON HE.HIST_ACTOR_USER_ID = HU.ID
LEFT JOIN WORKGROUP.PUBLIC.HIST_USERS HU2
ON HE.HIST_TARGET_USER_ID = HU2.ID
LEFT JOIN WORKGROUP.PUBLIC.USERS U
ON U.ID = HU.USER_ID
LEFT JOIN WORKGROUP.PUBLIC.USERS U2
ON U2.ID = HU2.USER_ID
LEFT JOIN WORKGROUP.PUBLIC.SYSTEM_USERS SU
ON SU.ID = U.SYSTEM_USER_ID
LEFT JOIN WORKGROUP.PUBLIC.SYSTEM_USERS SU2
ON SU2.ID = U2.SYSTEM_USER_ID
LEFT JOIN WORKGROUP.PUBLIC.HIST_SITES HS
ON HS.ID = HE.HIST_TARGET_SITE_ID
INNER JOIN
(SELECT MAX(HIST_WORKBOOK_ID) MAX_WB_ID, HW.NAME
FROM WORKGROUP.PUBLIC.HISTORICAL_EVENTS HE
LEFT JOIN WORKGROUP.PUBLIC.HISTORICAL_EVENT_TYPES HET
ON HE.HISTORICAL_EVENT_TYPE_ID = HET.TYPE_ID
LEFT JOIN WORKGROUP.PUBLIC.HIST_DATASOURCES HD
ON HD.ID = HE.HIST_DATASOURCE_ID
LEFT JOIN WORKGROUP.PUBLIC.HIST_VIEWS HV
ON HV.ID = HE.HIST_VIEW_ID
LEFT JOIN WORKGROUP.PUBLIC.HIST_WORKBOOKS HW
ON HW.ID = HE.HIST_WORKBOOK_ID
LEFT JOIN WORKGROUP.PUBLIC.HIST_SITES HS
ON HS.ID = HE.HIST_TARGET_SITE_ID
WHERE HET.TYPE_ID = 93 
AND SITE_ID IN (4,18)
GROUP BY HW.NAME) MAX_SUB
ON MAX_WB_ID = HW.ID
LEFT JOIN 
(SELECT HIST_WORKBOOK_ID WB_ID, HW.NAME
FROM WORKGROUP.PUBLIC.HISTORICAL_EVENTS HE
LEFT JOIN WORKGROUP.PUBLIC.HISTORICAL_EVENT_TYPES HET
ON HE.HISTORICAL_EVENT_TYPE_ID = HET.TYPE_ID
LEFT JOIN WORKGROUP.PUBLIC.HIST_DATASOURCES HD
ON HD.ID = HE.HIST_DATASOURCE_ID
LEFT JOIN WORKGROUP.PUBLIC.HIST_VIEWS HV
ON HV.ID = HE.HIST_VIEW_ID
LEFT JOIN WORKGROUP.PUBLIC.HIST_WORKBOOKS HW
ON HW.ID = HE.HIST_WORKBOOK_ID
LEFT JOIN WORKGROUP.PUBLIC.HIST_SITES HS
ON HS.ID = HE.HIST_TARGET_SITE_ID
WHERE HET.TYPE_ID IN (92, 82)
AND SITE_ID IN (4,18)) DELETED_SUB
ON HW.ID = WB_ID
WHERE HS.SITE_ID IN (4,18)
AND HET.TYPE_ID IN (93)
AND WB_ID IS NULL
AND HW.ID NOT IN (42,43,44)

UNION

SELECT 
USAGE_TYPE
,ROW_NUMBER() OVER () EVENT_ID
,EVENT_NAME
,ACTION_TYPE
,MMID
,USER_EMAIL
,USERNAME
,VIEW_NAME
,DATA_SOURCE_NAME
,WORKBOOK_NAME
,PROJECT_NAME
,CAST(EVENT_START_DATETIME AS DATE) EVENT_DATE
,EVENT_START_DATETIME
,EVENT_END_DATETIME
,FAIL_FLAG
,SITE_NAME
FROM
(SELECT DISTINCT
'LOAD' USAGE_TYPE
,CASE 
	WHEN LEFT(HTTP_REQUEST_URI,7) = '/views/' THEN 'Load Report'
	WHEN LEFT(HTTP_REQUEST_URI,21) = '/vizql/showadminview/' THEN 'Load Report'
	WHEN HTTP_REQUEST_URI LIKE '%bootstrapSession%' THEN 'Load Report'
	WHEN HTTP_REQUEST_URI LIKE '%set-parameter-value%' THEN 'Interaction'
	WHEN HTTP_REQUEST_URI LIKE '%select-region%' THEN 'Interaction'
	WHEN HTTP_REQUEST_URI LIKE '%categorical-filter%' THEN 'Interaction'
	WHEN HTTP_REQUEST_URI LIKE '%relative-date-filter%' THEN 'Interaction'
	WHEN HTTP_REQUEST_URI LIKE '%select' THEN 'Interaction'
	ELSE 'Other'
END EVENT_NAME
,NULL ACTION_TYPE
,HU.NAME MMID
,HU.EMAIL USER_EMAIL
,SU.FRIENDLY_NAME USERNAME
,CASE
	WHEN CURRENTSHEET = '' THEN NULL
	ELSE SUBSTRING(CURRENTSHEET, POSITION('/' IN CURRENTSHEET) + 1, LENGTH(CURRENTSHEET)) 
END VIEW_NAME 
,NULL DATA_SOURCE_NAME
,CASE
	WHEN CURRENTSHEET = '' THEN NULL
	ELSE SUBSTRING(CURRENTSHEET, 1, POSITION('/' IN CURRENTSHEET) - 1) 
END WORKBOOK_NAME
,P.NAME PROJECT_NAME
,HR.CREATED_AT EVENT_START_DATETIME
,HR.COMPLETED_AT EVENT_END_DATETIME
,0 FAIL_FLAG
,HTTP_REQUEST_URI
,HS.NAME SITE_NAME
FROM WORKGROUP.PUBLIC.HTTP_REQUESTS HR
LEFT JOIN WORKGROUP.PUBLIC.USERS U
ON U.ID = HR.USER_ID
LEFT JOIN WORKGROUP.PUBLIC.HIST_USERS HU
ON U.ID = HU.USER_ID
LEFT JOIN WORKGROUP.PUBLIC.SYSTEM_USERS SU
ON SU.ID = U.SYSTEM_USER_ID
LEFT JOIN WORKGROUP.PUBLIC.WORKBOOKS W
ON W.REPOSITORY_URL = CASE
	WHEN CURRENTSHEET = '' THEN NULL
	ELSE SUBSTRING(CURRENTSHEET, 1, POSITION('/' IN CURRENTSHEET) - 1) END
LEFT JOIN WORKGROUP.PUBLIC.PROJECTS P
ON P.ID = W.PROJECT_ID
LEFT JOIN WORKGROUP.PUBLIC.HIST_SITES HS
ON HR.SITE_ID = HS.SITE_ID
WHERE HR.SITE_ID IN (4,18)
AND HTTP_REQUEST_URI NOT LIKE '%tooltip%'
AND HTTP_REQUEST_URI NOT LIKE '%/tilecache/%'
AND HTTP_REQUEST_URI NOT LIKE '%/set-active-zone'
AND HTTP_REQUEST_URI NOT LIKE '%/tile/%'
AND HTTP_REQUEST_URI NOT LIKE '%browserBackButtonUndo=true%') SPEED_SUB