SELECT T1.Volumetric as PlanMetric
, T1.ShortDate
,T1.ShortDate as "Submit Date"
, T1.ChannelType as Channel
, T1.ProductType as Product
,'0' as "Submit Date Is Holiday"
, Measure
, DailyKPIPlan
, DailyMTDPlan
, DailyYTDPlan
FROM 

(SELECT DISTINCT T1.SHORTDATE
, CASE GROUPING(VOLUMETRIC) WHEN 1 THEN 'Total' ELSE VOLUMETRIC END AS Volumetric
, CASE GROUPING(PRODUCTTYPE) WHEN 1 THEN 'Total' ELSE PRODUCTTYPE END AS ProductType
, CASE GROUPING(CHANNELTYPE) WHEN 1 THEN 'Total' ELSE CHANNELTYPE END AS ChannelType
, SUM(DAILYKPIPLAN) AS DailyKPIPlan
, SUM(DAILYMTDPLAN) AS DailyMTDPlan
, SUM(DAILYYTDPLAN) AS DailyYTDPlan
FROM PROD_DMA_VW.PRD_KPI_PLAN_DATA_VW T1       
Inner Join PROD_DMA_VW.Date_DIM_VW as T2 ON T1.ShortDate = T2.ShortDate    
WHERE CHANNELTYPE <> 'Total'
AND DEPARTMENTID = 47
AND IsHoliday = 0
GROUP BY ROLLUP(VOLUMETRIC,CHANNELTYPE,PRODUCTTYPE),1) T1

Left Join
(
SELECT DISTINCT CASE GROUPING(T1.VOLUMETRIC) WHEN 1 THEN 'Total' ELSE T1.VOLUMETRIC END AS Volumetric
, CASE GROUPING(CAST(T1.ShortDate AS VARCHAR(10))) WHEN 1 THEN 'Total' ELSE CAST(T1.ShortDate AS VARCHAR(10)) END AS ShortDate
, CASE GROUPING(T1.PRODUCTTYPE) WHEN 1 THEN 'Total' ELSE T1.PRODUCTTYPE END AS ProductType
, CASE GROUPING(T1.CHANNELTYPE) WHEN 1 THEN 'Total' ELSE T1.CHANNELTYPE END AS ChannelType
, SUM(T1.MEASURE) AS Measure
FROM 
(
SELECT 'Submitted WTD Prem' AS VOLUMETRIC
, CAST(NEWBUSINESSSUBMITDATE AS DATE) AS SHORTDATE
, T2.MAJOR_PROD_NME AS ProductType
, CASE WHEN To_Number (T1.AGENCYNUMBER) IS NULL THEN 'SDP' ELSE 'MMFA' END AS ChannelType
, SUM(FACE_AMOUNT) AS Measure
FROM PROD_DMA_VW.ANB_APPLICATION_FCT_VW T1
LEFT JOIN PROD_USIG_STND_VW.AGMT_CMN_VW T2 ON T1.AGREEMENTID = T2.AGREEMENT_ID
GROUP BY 1,2,3,4

UNION

SELECT 'Reported Premium' AS VOLUMETRIC
, CYCLE_DATE AS SHORTDATE
, T2.MAJOR_PROD_NME AS ProductType
, CASE WHEN TO_NUMBER(T7.AGT_WRTG_AGY_CD) IS NULL THEN 'SDP' ELSE 'MMFA' END AS ChannelType
, SUM(TOTAL_DOLLAR_AMOUNT) AS Measure
FROM PROD_USIG_STND_VW.AGMT_PDCR_FIN_TXN_CMN_VW T1
INNER JOIN PROD_USIG_STND_VW.AGMT_CMN_VW T2 ON T1.AGREEMENT_ID = T2.AGREEMENT_ID
LEFT JOIN (SELECT T1.AGREEMENT_ID, T2.BUSINESS_PARTNER_ID, AGT_WRTG_AGY_CD
                                        FROM PROD_USIG_STND_VW.PDCR_AGMT_HIST_VW T1
                                        LEFT JOIN PROD_USIG_STND_VW.PDCR_DEMOGRAPHICS_VW T2 ON T1.BUSINESS_PARTNER_ID = T2.BUSINESS_PARTNER_ID
                                        WHERE PRTY_AGMT_RLE_CD = 'AGT' AND PRTY_AGMT_RLE_STYP_CD = 'SVC'
                                        QUALIFY ROW_NUMBER() OVER (PARTITION BY AGREEMENT_ID ORDER BY PDCR_AGMT_HIST_TO_DT DESC) = 1) T7 ON T1.AGREEMENT_ID = T7.AGREEMENT_ID                                                                         
WHERE BUSINESS_EVENT_CODE In ('75','76','78','79')
AND T1.SRC_SYS_ID IN (57,68,72,73,81,82,83) --AND T1.AGREEMENT_SOURCE_CD IN ('LIFCOM','VNTGKC','ASIA','ANNWMA','RPS','SE2','AWF')
AND TRANS_AMOUNT_TYPE = 'TNA' AND TXN_DURATION = 1
AND EXTRACT(YEAR FROM ISSUE_DT) = EXTRACT(YEAR FROM CYCLE_DATE)
GROUP BY 1,2,3,4

UNION

SELECT  'Submitted Counts' AS VOLUMETRIC
, CAST(NEWBUSINESSSUBMITDATE AS DATE) AS SHORTDATE
, T2.MAJOR_PROD_NME AS ProductType
, CASE WHEN TO_NUMBER(T1.AGENCYNUMBER) IS NULL THEN 'SDP' ELSE 'MMFA' END AS ChannelType
, CAST (COUNT(NEWBUSINESSSUBMITDATE) AS DECIMAL(8,2))AS Measure
FROM PROD_DMA_VW.ANB_APPLICATION_FCT_VW T1
LEFT JOIN PROD_USIG_STND_VW.AGMT_CMN_VW T2 ON T1.AGREEMENTID = T2.AGREEMENT_ID
GROUP BY 1,2,3,4

UNION 

SELECT 'Issued Counts' AS VOLUMETRIC
, CAST(IssueDate AS DATE) AS SHORTDT
, T2.MAJOR_PROD_NME AS ProductType
, CASE WHEN TO_NUMBER(T1.AGENCYNUMBER) IS NULL THEN 'SDP' ELSE 'MMFA' END AS ChannelType
,Cast (COUNT(ISSUEDATE) as DECIMAL(8,2)) AS Measure
FROM PROD_DMA_VW.ANB_APPLICATION_FCT_VW T1
LEFT JOIN PROD_USIG_STND_VW.AGMT_CMN_VW T2 ON T1.AGREEMENTID = T2.AGREEMENT_ID
GROUP BY 1,2,3,4
) T1

WHERE T1.SHORTDATE >= Current_Date - INTERVAL '5' YEAR
AND ProductType IS NOT NULL AND ChannelType IS NOT NULL

GROUP BY ROLLUP(T1.VOLUMETRIC,CAST(T1.ShortDate AS VARCHAR(10)),T1.CHANNELTYPE,T1.PRODUCTTYPE)

) T2
ON T1.VOLUMETRIC = T2.VOLUMETRIC AND T2.SHORTDATE = CAST(T1.SHORTDATE AS VARCHAR(10)) 
AND T1.PRODUCTTYPE = T2.PRODUCTTYPE AND T1.CHANNELTYPE = T2.CHANNELTYPE