--SE2 for BINGO Extract
SELECT DISTINCT
DISTRIBUTOR
, CHANNEL
, PRODUCT
, T1.AGREEMENTID
, PolicyNumber
, T1.ORDERENTRYID
, RESIDENCESTATE
, T1.AGENTID
, T1.AGENCYNUMBER
, T1.Firm
, T1.FirmNum
, FirmName
, RegionName
, Product Category
, T1.ISSUEDATE
, NIGODATE
, T1.NEWBUSINESSSUBMITDATE
, SUITABILITYSUBMITDATE
, BINGODATE
, BINGOSTATUS
, BINGOINDICATOR
, (BINGODATE - NIGODATE) NIGOResolution
, NIGOCATEGORY
, NIGODESCRIPTION
, DocumentTypeCode
FROM PROD_DMA_VW.ANB_APPLICATION_RPT_VW T1

LEFT JOIN (SELECT DISTINCT AGREEMENTID
							, CAST(MIN(NIGODate) OVER (PARTITION BY AGREEMENTID) AS DATE) AS NIGODate
							, MAX(NIGOResolutionDate) OVER (PARTITION  BY AGREEMENTID) AS NIGOResolvedDate
							, T2.NIGODESCRIPTION
							, NIGOCategory
							, ReasonDescription
							, DocumentTypeCode
						FROM PROD_DMA_VW.ANB_NIGO_FCT_VW T1
						INNER JOIN PROD_DMA_VW.ANN_NIGO_REASON_LOV_VW T2 ON T2.NIGOUUID = T1.NIGOUUID
						WHERE T1.SYSTEMID = 34
						AND GROUPTYPE LIKE 'NEW B%') T10 ON T1.AGREEMENTID = T10.AGREEMENTID 
		
WHERE  T1.ORIGINALORDERSUBMITDATE >= CURRENT_DATE - INTERVAL '1' YEAR -- CHANGE THE INTERVAL AS YOU SEE FIT ;

