SELECT DISTINCT
DISTRIBUTOR
, CHANNEL
, PRODUCT
, T1.AGREEMENTID
, PolicyNumber
, T1.ORDERENTRYID
, RESIDENCESTATE
, T1.AGENTID
, T1.AGENCYNUMBER
, T1.Firm
, T1.FirmNum
, FirmName
, RegionName
, Product Category
, T1.ISSUEDATE
, NIGODATE
, T1.NEWBUSINESSSUBMITDATE
, SUITABILITYSUBMITDATE
, BINGODATE
, BINGOSTATUS
, BINGOINDICATOR
, (BINGODATE - NIGODATE) NIGOResolution
, NIGOCATEGORY
, NIGODESCRIPTION
, DocumentTypeCode
FROM PROD_DMA_VW.ANB_APPLICATION_RPT_VW T1

LEFT JOIN (SELECT DISTINCT AGREEMENTID
							, CAST(MIN(NIGODate) OVER (PARTITION BY AGREEMENTID) AS DATE) AS NIGODate
							, MAX(NIGOResolutionDate) OVER (PARTITION  BY AGREEMENTID) AS NIGOResolvedDate
							, T2.NIGODESCRIPTION
							, NIGOCategory
							, ReasonDescription
							, DocumentTypeCode
						FROM PROD_DMA_VW.ANB_NIGO_FCT_VW T1
						INNER JOIN PROD_DMA_VW.ANN_NIGO_REASON_LOV_VW T2 ON T2.NIGOUUID = T1.NIGOUUID
						WHERE T1.SYSTEMID = 34
						AND GROUPTYPE LIKE 'NEW B%') T10 ON T1.AGREEMENTID = T10.AGREEMENTID 
		
WHERE  T1.ORIGINALORDERSUBMITDATE >= CURRENT_DATE - INTERVAL '1' YEAR -- CHANGE THE INTERVAL AS YOU SEE FIT ;


--INITIAL REVIEW BINGO

SELECT DISTINCT
ApplicationID
, StateCode
, IRMarketTypeName
, SuitabilityIndicator
, IGOIndicator
, DISTRIBUTOR
, Product
, Product Category
, T1.AgentID
, T1.AGENTID
, T1.AGENCYNUMBER AS FIRMNUM
, Firm
, T2.FirmName
,  RegionName
, DISTRIBUTOR
, Channel
, NEWBUSINESSSUBMITDATE
, ISSUEDATE
, NIGOReason
, CAST(T1.CreatedAtDateTimestamp AS DATE) NIGODATE
, CAST(ISSUEDATE AS DATE) BINGODATE
, (BINGODATE - NIGODATE) NIGOResolution
FROM	PROD_DMA_VW.ANB_IR_NIGO_REASON_TOKEN_VW T1
LEFT JOIN PROD_DMA_VW.ANB_APPLICATION_RPT_VW T2 ON T2.INITIALREVIEWID = T1.INITIALREVIEWID
LEFT JOIN PROD_DMA_VW.FIRM_DIM_VW T3 ON T1.AGENCYNUMBER = T3.ORIGINALFIRMNUMBER
LEFT JOIN PROD_USIG_CMN_VW.PRODUCT_TRANSLATOR_VW T4 ON CAST(T4.PROD_ID AS INTEGER)= T1.IRPRODUCTID
LEFT JOIN PROD_DMA_VW.ANB_IR_MARKET_TYPES_VW T5 ON T5.IRMARKETTYPEID = T1.IRMARKETTYPEID
LEFT JOIN PROD_DMA_VW.ANB_IR_QUESTIONS_VW T6 ON T6.QUESTIONNAME = T1.NIGOREASON
WHERE T2.INITIALREVIEWID IS NOT NULL
