--SE2
SELECT DISTINCT
CASE WHEN TO_NUMBER(T1.AGENCYNUMBER) IS NULL THEN 'SDP'
		WHEN CAS_IND = 'N' AND TO_NUMBER(T1.AGENCYNUMBER) IS NOT NULL THEN 'CAB'	
		WHEN TO_NUMBER(T1.AGENCYNUMBER) IS NOT NULL THEN 'CAS'
		ELSE 'Unknown' END
, CASE WHEN TO_NUMBER(T1.AGENCYNUMBER) IS NULL THEN 'SDP' ELSE 'MMFA' END 
, CASE WHEN TO_NUMBER(T1.AGENCYNUMBER) IS NULL THEN 'SDP' ELSE 'Non-SDP' END 
, OREPLACE(COALESCE(T4.PRODUCTNAME,T3.PROD_TYP_NME),'MassMutual ','') 
,T1.AGREEMENTID
, TRIM(LEADING '0' FROM T1.HOLDINGKEY) PolicyNumber
, T1.ORDERENTRYID
, CASE WHEN T5.NBPURCHASEWITHAPPINDICATOR = 1 THEN 'NB Purchase w App'
	WHEN T5.INCOMINGTRANSFERINDICATOR = 1 THEN 'Incoming Transfer'
	WHEN T5.ANNUITYAPPINDICATOR = 1 THEN 'Annuity Application'
	WHEN T5.SDELECTAPPINDICATOR = 1 THEN 'SD Elect App'
	WHEN T5.NBREG60INDICATOR = 1 THEN 'NB Reg 60'
	WHEN T5.EXCLUDEDINDICATOR = 1 THEN 'Excluded'
	WHEN T5.OVERLAPINDICATOR = 1 THEN 'Overlap'
	ELSE 'N/A' END
, CTRT_JURISDICTION
, RES_JURISDICTION
, T1.AGENTID
, T1.AGENCYNUMBER
, CASE WHEN FirmCodeWithPrefix IS NULL THEN FirmCode
	ELSE FirmCodeWithPrefix END AS Firm
, CASE WHEN T1.AGENCYNUMBER = 'FIL' THEN '244' 
	ELSE T1.AGENCYNUMBER END AS FirmNum
, CASE WHEN FirmNum = 'EDJ' THEN '999 - Edward Jones'
	WHEN FirmCodeWithPrefix IS NULL AND FirmNum IS NULL THEN '999 - Unknown'
	WHEN FirmCodeWithPrefix IS NULL THEN '999 - ' || FirmNum
	ELSE FirmDisplayName END AS FirmName
, CASE WHEN DistributionChannelType = 'DISO' OR FirmCodeWithPrefix IN ('A000','A199') THEN 'CLOSED AGENCIES'
	WHEN DistributionChannelType IN ('DDC','OTHR') OR OriginalFirmCodeWithPrefix IN ('A113','A119','A226','A244','A249') THEN 'Direct Brokerage'
	WHEN OriginalFirmCodeWithPrefix = 'A109' THEN 'Lifebridge Agency'
	WHEN FirmCodeWithPrefix IN ('A020','A028') THEN 'UPPER MIDWEST'
	WHEN FirmCodeWithPrefix IN ('A253','A275') THEN 'MIDWEST-SOCA'
	WHEN FirmCodeWithPrefix = 'A271' THEN 'SE-MW'
	WHEN FirmCodeWithPrefix = 'A262' THEN 'VIRGINA-NORTH'
	WHEN FirmCode IN ('FIL','FILI') THEN 'Fidelity'
	WHEN FirmCodeWithPrefix IS NULL THEN 'UNKNOWN' 
	ELSE Region END AS RegionName
, COALESCE(CASE WHEN COALESCE(T4.PRODUCTNAME,T3.PROD_TYP_NME) LIKE '%RetireEase%' THEN 'Income Annuity'
						WHEN COALESCE(T4.PRODUCTNAME,T3.PROD_TYP_NME) LIKE '%Index Horizons%' THEN 'Fixed Indexed'
						ELSE T3.MAJOR_PROD_NME END,T4.PRODUCTTYPE) AS "Product Category"
, CAST(ISSUEDATE AS DATE) 
, NIGODATE
, COALESCE(ISSUEDATE,CAST(APPLICATIONCHANGEDATE AS DATE)) 
, COALESCE((CASE WHEN NIGORESOLVEDDATE = '0001-01-01' THEN NULL ELSE NIGORESOLVEDDATE END),CAST(NEWBUSINESSSUBMITDATE AS DATE) ) AS BINGODATE
, CASE WHEN NIGODATE IS NOT NULL THEN 'Nigo' ELSE 'Bingo' END 
, CASE WHEN NIGODATE IS NOT NULL THEN '0' ELSE '1' END 
, (BINGODATE - NIGODATE) NIGOResolution
, NIGOCATEGORY
, NIGODESCRIPTION
FROM PROD_DMA_VW.ANB_APPLICATION_FCT_VW T1

LEFT JOIN (SELECT AGREEMENT_ID, SUM(TRANSFER_AMOUNT) AS TRANSFER_AMOUNT FROM PROD_USIG_STND_VW.AGMT_REPLACEMENTS_CMN_VW GROUP BY 1) T2 ON T1.AGREEMENTID = T2.AGREEMENT_ID

LEFT JOIN PROD_USIG_STND_VW.AGMT_CMN_VW T3 ON T1.AGREEMENTID = T3.AGREEMENT_ID

LEFT JOIN PROD_DMA_VW.IPIPELINE_ORDERS_VW T4 ON T1.ORDERENTRYID = OREPLACE(T4.ORDERENTRYID,'-','')

LEFT JOIN (SELECT * FROM PROD_DMA_VW.SE2_DOC_TYPE_HISTORY_VW WHERE TYPE2CURRENTFLAG = 1) T5 ON TRIM(LEADING '0' FROM T1.HOLDINGKEY) = T5.CONTRACTNUMBER

LEFT JOIN PROD_DMA_VW.FIRM_DIM_VW T8 ON FirmNum = T8.ORIGINALFIRMCODE					

LEFT JOIN PROD_USIG_STND_VW.PDCR_DEMOGRAPHICS_VW T9 ON T1.AGENTID = SUBSTR(TRIM(T9.BUSINESS_PARTNER_ID), CHARACTER_LENGTH(TRIM(T9.BUSINESS_PARTNER_ID)) - 5 FOR 6)				
	
LEFT JOIN (SELECT DISTINCT AGREEMENTID
							, CAST(MIN(NIGODate) OVER (PARTITION BY AGREEMENTID) AS DATE) AS NIGODate
							, MAX(NIGOResolutionDate) OVER (PARTITION  BY AGREEMENTID) AS NIGOResolvedDate
							, T2.NIGODESCRIPTION
							, NIGOCategory
							, ReasonDescription
						FROM PROD_DMA_VW.ANB_NIGO_FCT_VW T1
						INNER JOIN PROD_DMA_VW.ANN_NIGO_REASON_LOV_VW T2 ON T2.NIGOUUID = T1.NIGOUUID
						WHERE T1.SYSTEMID = 34
						AND GROUPTYPE LIKE 'NEW B%') T10 ON T1.AGREEMENTID = T10.AGREEMENTID 
		
WHERE T3.AGREEMENT_SOURCE_CD = 'SE2'
AND ORDERSUBMITDATE >= CURRENT_DATE - INTERVAL '1' YEAR -- CHANGE THE INTERVAL AS YOU SEE FIT ;

----Initial Review

SELECT DISTINCT
ApplicationID
, StateCode
, IRMarketTypeName
, SuitabilityIndicator
, IGOIndicator
, OREPLACE(PROD_TYP_NME,'MassMutual ','') AS Product
, CASE WHEN PROD_TYP_NME LIKE '%RetireEase%' THEN 'Income Annuity'
	WHEN PROD_TYP_NME LIKE '%Index Horizons%' THEN 'Fixed Indexed'
	ELSE MAJOR_PROD_NME 
END AS "Product Category"
, T1.AgentID
, T1.AGENTID
, T1.AGENCYNUMBER AS FIRMNUM
, CASE WHEN FirmCodeWithPrefix IS NULL THEN FirmCode
			ELSE FirmCodeWithPrefix END AS Firm
, CASE WHEN FirmNum = 999 THEN '999 - Edward Jones'
			WHEN FirmCodeWithPrefix IS NULL AND FirmNum IS NULL THEN '999 - Unknown'
			WHEN FirmCodeWithPrefix IS NULL THEN '999 - ' || FirmNum
  ELSE FirmDisplayName END AS FirmName
, CASE WHEN DistributionChannelType = 'DISO' OR FirmCodeWithPrefix IN ('A000','A199') THEN 'CLOSED AGENCIES'
			WHEN DistributionChannelType IN ('DDC','OTHR') OR OriginalFirmCodeWithPrefix IN ('A113','A119','A226','A244','A249') THEN 'Direct Brokerage'
			WHEN OriginalFirmCodeWithPrefix = 'A109' THEN 'Lifebridge Agency'
			WHEN FirmCodeWithPrefix IN ('A020','A028') THEN 'UPPER MIDWEST'
			WHEN FirmCodeWithPrefix IN ('A253','A275') THEN 'MIDWEST-SOCA'
			WHEN FirmCodeWithPrefix = 'A271' THEN 'SE-MW'
			WHEN FirmCodeWithPrefix = 'A262' THEN 'VIRGINA-NORTH'
			WHEN FirmCode IN ('FIL','FILI') THEN 'Fidelity'
			WHEN FirmCodeWithPrefix IS NULL THEN 'UNKNOWN' 
  ELSE Region END AS RegionName
, CASE WHEN T1.AGENCYNUMBER IS NULL THEN 'SDP' ELSE 'MMFA' END AS Channel
, CASE WHEN T1.AGENCYNUMBER IS NULL THEN 'SDP' ELSE 'Non-SDP' END AS "Channel Type"
, CAST(NEWBUSINESSSUBMITDATE AS DATE) NEWBUSINESSSUBMITDATE
, CAST(ISSUEDATE AS DATE) ISSUEDATE
, NIGOReason
, CAST(T1.CreatedAtDateTimestamp AS DATE) NIGODATE
, CAST(NEWBUSINESSSUBMITDATE AS DATE) BINGODATE
, (BINGODATE - NIGODATE) NIGOResolution
FROM	PROD_DMA_VW.ANB_IR_NIGO_REASON_TOKEN_VW T1
LEFT JOIN PROD_DMA_VW.ANB_APPLICATION_FCT_VW T2 ON T2.INITIALREVIEWID = T1.INITIALREVIEWID
LEFT JOIN PROD_DMA_VW.FIRM_DIM_VW T3 ON T1.AGENCYNUMBER = T3.ORIGINALFIRMNUMBER
LEFT JOIN PROD_USIG_CMN_VW.PRODUCT_TRANSLATOR_VW T4 ON CAST(T4.PROD_ID AS INTEGER)= T1.IRPRODUCTID
LEFT JOIN PROD_DMA_VW.ANB_IR_MARKET_TYPES_VW T5 ON T5.IRMARKETTYPEID = T1.IRMARKETTYPEID
LEFT JOIN PROD_DMA_VW.ANB_IR_QUESTIONS_VW T6 ON T6.QUESTIONNAME = T1.NIGOREASON
WHERE T2.INITIALREVIEWID IS NOT NULL
