SELECT T1.OrderEntryID
, T1.OriginalOrderSubmitDate AS "Suitability Submit Date"
, T1.PendDate
, T1.CancelReworkDate
, T1.TransmitDate
, T1.ApprovedDate
, T1.RejectDate
, T1.CancelDate
,CASE WHEN COALESCE(T1.ApprovedDate,T1.TransmitDate) IS NOT NULL THEN 'Approved'
            WHEN T1.RejectDate IS NOT NULL THEN 'Rejected'
            WHEN T1.CancelDate IS NOT NULL THEN 'Cancelled'
END AS "Order Status"

, COALESCE(T1.TransmitDate, T1.ApprovedDate, T1.RejectDate, T1.CancelDate) AS "Order Status Date"
, T1.SourceSystemID
, T1.RunID
, T1.UpdateRunID
, T1.TransDate
--, T2.Distributor
, CASE WHEN TO_NUMBER(T2.AGENCYNUMBER) IS NULL THEN 'SDP' ELSE 'MMFA' END AS "Channel"
, CASE WHEN TO_NUMBER(T2.AGENCYNUMBER) IS NULL THEN 'SDP' ELSE 'Non-SDP' END AS "Channel Type"
, OREPLACE(PRODUCTNAME,'MassMutual ','') AS "Product"
, COALESCE(CASE WHEN PRODUCTNAME LIKE '%RetireEase%' THEN 'Income Annuity'
						WHEN PRODUCTNAME LIKE '%Index Horizons%' THEN 'Fixed Indexed' END,T2.PRODUCTTYPE) AS "Product Category"
, T2.AgentID
, T3.HLDG_KEY AS "Holding Key"
--, T2.NewBusinessSubmitDate
, T2.AutoApprovedIndicator
, CASE WHEN T5.NBPURCHASEWITHAPPINDICATOR = 1 THEN 'NB Purchase w App'
	WHEN T5.INCOMINGTRANSFERINDICATOR = 1 THEN 'Incoming Transfer'
	WHEN T5.ANNUITYAPPINDICATOR = 1 THEN 'Annuity Application'
	WHEN T5.SDELECTAPPINDICATOR = 1 THEN 'SD Elect App'
	WHEN T5.NBREG60INDICATOR = 1 THEN 'NB Reg 60'
	WHEN T5.EXCLUDEDINDICATOR = 1 THEN 'Excluded'
	WHEN T5.OVERLAPINDICATOR = 1 THEN 'Overlap'
	ELSE 'N/A' END AS "NB Doc Type"
, CASE WHEN NIGODATE IS NOT NULL THEN 'Nigo' ELSE 'Bingo' END AS "BINGO Status"
, CASE WHEN NIGODATE IS NOT NULL THEN '0' ELSE '1' END AS "BINGO Indicator"
, CAST(T1.TransmitDate AS DATE) - CAST(T1.OriginalOrderSubmitDate AS DATE) AS SuitabilityCycleTime
, CAST(T1.TransmitDate AS DATE) - CAST(T1.PendDate AS DATE) AS InitialReviewCycleTime

FROM PROD_DMA_VW.IPIPELINE_ORDER_FCT_VW T1

LEFT JOIN PROD_DMA_VW.IPIPELINE_ORDERS_VW T2 ON T1.ORDERENTRYID = OREPLACE(T2.ORDERENTRYID,'-','')

LEFT JOIN (SELECT DISTINCT (SUBSTR(TRIM(TRAILING FROM DISTRIBUTION_TRANS_ID),1,10)) ORDER_ENTRY_ID, AGREEMENT_ID, HLDG_KEY
								, ROW_NUMBER() OVER (PARTITION BY ORDER_ENTRY_ID ORDER BY TRANS_DT) SEQ_NUM
						FROM PROD_USIG_STND_VW.AGMT_REPLACEMENTS_CMN_VW T1
						WHERE HLDG_KEY_SFX = ' ' AND SRC_SYS_ID = 57 AND ORDER_ENTRY_ID IS NOT NULL AND ORDER_ENTRY_ID <> ' ' AND ORDER_ENTRY_ID NOT LIKE ALL ('0188%','MMFG%')
						QUALIFY ROW_NUMBER() OVER (PARTITION BY AGREEMENT_ID ORDER BY TRANS_DT) = 1) T3 ON T1.ORDERENTRYID = T3.ORDER_ENTRY_ID
						
LEFT JOIN (SELECT DISTINCT AGREEMENTID
							, CAST(MIN(NIGODate) OVER (PARTITION BY AGREEMENTID) AS DATE) AS NIGODate
							, MAX(NIGOResolutionDate) OVER (PARTITION  BY AGREEMENTID) AS NIGOResolvedDate
						FROM PROD_DMA_VW.ANB_NIGO_FCT_VW WHERE SYSTEMID = 34) T4 ON T3.AGREEMENT_ID = T4.AGREEMENTID 
						
LEFT JOIN (SELECT * FROM PROD_DMA_VW.SE2_DOC_TYPE_HISTORY_VW WHERE TYPE2CURRENTFLAG = 1) T5 ON TRIM(LEADING '0' FROM T3.HLDG_KEY) = T5.CONTRACTNUMBER

WHERE CAST("Order Status Date" AS DATE) >= '2019-07-01' 





/*SELECT *
FROM PROD_DMA_VW.IPIPELINE_ORDER_FCT_VW T1
INNER JOIN PROD_DMA_VW.IPIPELINE_ORDERS_VW T2 ON T1.ORDERENTRYID = OREPLACE(T2.ORDERENTRYID,'-','')
WHERE T1.PENDDATE IS NULL AND T2.ELECTRONICSUBMITDATE IS NOT NULL*/