SELECT DISTINCT --Bill's Test Notes

--Suitability Current Status   ---CT Dash

--Suitability Last Status Date  ---CT Dash

--Suitability Transmit Date  ---CT Dash

--NewBusiness Status  ---SM Dash

--Suitability Current Status  -- SM Dash

'2010-05-01' as "Suitability Throughput"

,'10' as "CalDayssuitCmpltToNBRcvd"

,'0' as "IR NIGO Indicator"

,(SELECT PreviousBusinessDay

   FROM PROD_DMA_VW.DATE_DIM_VW

   WHERE ShortDate = CAST(Current_Date AS DATE)) AS PreviousBusinessDayOfToday

,'Pending New Business,Pending Suitability' as "Pending Status"

,'Received, Not Approved or In Good Order, Awaiting Funds' as "Pending New Business Contract Status"

, CASE WHEN TO_NUMBER(T1.AGENCYNUMBER) IS NULL THEN 'SDP'

WHEN CAS_IND = 'N' AND TO_NUMBER(T1.AGENCYNUMBER) IS NOT NULL THEN 'CAB'

WHEN TO_NUMBER(T1.AGENCYNUMBER) IS NOT NULL THEN 'CAS'

ELSE 'Unknown' END AS Distributor

, CASE WHEN TO_NUMBER(T1.AGENCYNUMBER) IS NULL THEN 'SDP' ELSE 'MMFA' END AS Channel

, CASE WHEN TO_NUMBER(T1.AGENCYNUMBER) IS NULL THEN 'SDP' ELSE 'Non-SDP' END AS "Channel Type"

, OREPLACE(COALESCE(T4.PRODUCTNAME,T3.PROD_TYP_NME,T13.PROD_TYP_NME),'MassMutual ','') AS "Product"

,T9.lst_NM||', '||T9.First_nm as Advisor

,Null as "Region"

,( SELECT IsHoliday

FROM PROD_DMA_VW.DATE_DIM_VW

WHERE CAST(ISSUEDATE AS DATE) = ShortDate

) AS "Issue Date Is Holiday"

,( SELECT IsHoliday

FROM PROD_DMA_VW.DATE_DIM_VW

WHERE CAST(COALESCE(ORIGINALORDERSUBMITDATE,ORDERSUBMITDATE,NEWBUSINESSSUBMITDATE) AS DATE) = ShortDate

) AS "Submit Date Is Holiday"

,T1.AGREEMENTID

, T12.PROD_CD

, TRIM(LEADING '0' FROM HOLDINGKEY) as HOLDINGKEY

, T1.ORDERENTRYID

,T4.AUTOAPPROVEDINDICATOR

,Case

When T4.AUTOAPPROVEDINDICATOR = 0 then 'No'

When T4.AUTOAPPROVEDINDICATOR = 1 then 'Yes'

End AS "SuitabilityAutoApproveIndicator"

, COALESCE(TRANSFER_AMOUNT,TOTALINITIALPREMIUM) AS "Anticipated Premium"

,T11."Deposit Amount"

, CASE WHEN T5.NBPURCHASEWITHAPPINDICATOR = 1 THEN 'NB Purchase w App'

WHEN T5.INCOMINGTRANSFERINDICATOR = 1 THEN 'Incoming Transfer'

WHEN T5.ANNUITYAPPINDICATOR = 1 THEN 'Annuity Application'

WHEN T5.NBREG60INDICATOR = 1 THEN 'NB Reg 60'

ELSE 'N/A' END AS "Doc Type"

, CTRT_JURISDICTION AS "Contract State"

, RES_JURISDICTION AS "Resident State"

, T1.AGENTID

, T1.AGENCYNUMBER AS "Firm"

, CASE WHEN T1.AGENCYNUMBER = 'EDJ' THEN '999 - Edward Jones'

WHEN OriginalFirmCodeWithPrefix IS NULL AND T1.AGENCYNUMBER IS NULL THEN '999 - Unknown'

WHEN OriginalFirmCodeWithPrefix IS NULL THEN '999 - ' || T1.AGENCYNUMBER

ELSE FirmDisplayName END AS "Firm Name"

, COALESCE(CASE WHEN COALESCE(T3.PROD_TYP_NME,T13.PROD_TYP_NME) LIKE '%RetireEase%' THEN 'Income Annuity'

WHEN COALESCE(T3.PROD_TYP_NME,T13.PROD_TYP_NME) = 'Index Horizons' THEN 'Fixed Indexed'

ELSE COALESCE(T3.MAJOR_PROD_NME,T13.MAJOR_PROD_NME) END,T4.PRODUCTTYPE) AS "Product Category"

, TRIM(LEADING '0' FROM HOLDINGKEY) AS "Policy Number"

, CAST(SUITABILITYAPPROVEDDATE AS DATE) AS "Suitability Aprov Date"

, CAST(ORIGINALORDERSUBMITDATE AS DATE) AS ORIGINAL_ORDER_SUBMIT_DT

, CAST(COALESCE(ORIGINALORDERSUBMITDATE,ORDERSUBMITDATE) AS DATE) AS "Suitability Submit Date"

, CAST(APPSIGNDATE AS DATE) AS "APP_SIGN_DT"

, CAST(NEWBUSINESSSUBMITDATE AS DATE) AS "NB Submit Date"

, CAST(ISSUEDATE AS DATE) AS "Issue Date"

,CASE WHEN "Issue Date" >= '2018-08-01' THEN 1 ELSE 0 END AS "Issue Count for BINGO Rate"

, CAST(REJECTDATE AS DATE) AS "Reject Date"

, CAST(WITHDRAWNDATE AS DATE) AS WITHDRAW_DT

, CAST(PAWDATE AS DATE) AS PAW_DT

, PAW_DT + 1 AS TOA_DT

, APPLICATIONCHANGEDATE

, CAST(CURRENT_DATE AS DATE) AS TODAY

, CAST(COALESCE(ORIGINALORDERSUBMITDATE,ORDERSUBMITDATE,NEWBUSINESSSUBMITDATE) AS DATE) AS "Submit Date"

, FIRST_NIGO_DT

, COALESCE(ISSUEDATE,CAST(APPLICATIONCHANGEDATE AS DATE)) AS NB_END_DT

, COALESCE((CASE WHEN NIGO_RES_DT = '0001-01-01' THEN NULL ELSE NIGO_RES_DT END),NB_END_DT,"NB Submit Date") AS BINGO_DT

, CASE WHEN FIRST_NIGO_DT IS NOT NULL THEN 'Nigo' ELSE 'Bingo' END AS "Bingo Status"

, CASE WHEN FIRST_NIGO_DT IS NOT NULL THEN '1' ELSE '0' END AS "BINGO Indicator"



, TODAY - "Submit Date" AS CalDaysSinceSubmit

, TODAY - "NB Submit Date" AS CalDaysSinceNBSubmit

, CAST(ISSUEDATE AS DATE) - APP_SIGN_DT AS CalDaysSignToIssue

, APP_SIGN_DT - "Submit Date" AS CalDaysSignToSubmit

, ORIGINAL_ORDER_SUBMIT_DT - APP_SIGN_DT AS CalDaysAppSignToSuitSubmit

, "NB Submit Date" - APP_SIGN_DT AS CalDaysSignToNBSubmit





, CAST(ISSUEDATE AS DATE) - "Submit Date" AS "Submit to Issue Cycle Time"

, "Suitability Aprov Date" - "Submit Date" AS CalDaysSubmitToSuitApvd

, "NB Submit Date"- "Submit Date" AS CalDaysSubmtToNBSubmit







, CAST(ISSUEDATE AS DATE) - "NB Submit Date" AS CalDaysNBRcvdToIssued

, BINGO_DT - "NB Submit Date" AS NBSubmitToBINGO

, "NB Submit Date" - PAW_DT AS CalDaysNBSubmitToPAW







, CAST(SUITABILITYAPPROVEDDATE AS DATE) - "Suitability Submit Date" AS CalDaysSuitSubmitToSuitApvd

, "NB Submit Date" -"Suitability Aprov Date" AS CalDaysSuitApvdToNBSubmit

, CAST(ORDERCHANGEDATE AS DATE) - CAST(SUITABILITYAPPROVEDDATE AS DATE) AS CalDaysSuitApvdToSuitTransmit

, CAST(SUITABILITYAPPROVEDDATE AS DATE) - "Suitability Submit Date" AS CalDaysSuitSubmitToSuitTransmit

, CAST(ISSUEDATE AS DATE) - "Suitability Submit Date" AS CalDaysSuitSubmitToIssue





, PAW_DT - BINGO_DT AS CalDaysBINGOToPAW

, TOA_DT - BINGO_DT AS CalDaysBINGOToTOA

, CAST(ISSUEDATE AS DATE) - TOA_DT AS CalDaysTOAToIssue

FROM PROD_DMA_VW.ANB_APPLICATION_FCT_VW T1

LEFT JOIN (SELECT AGREEMENT_ID, SUM(TRANSFER_AMOUNT) AS TRANSFER_AMOUNT FROM PROD_USIG_STND_VW.AGMT_REPLACEMENTS_CMN_VW GROUP BY 1) T2 ON T1.AGREEMENTID = T2.AGREEMENT_ID

LEFT JOIN PROD_USIG_STND_VW.AGMT_CMN_VW T3 ON T1.AGREEMENTID = T3.AGREEMENT_ID

LEFT JOIN PROD_DMA_VW.IPIPELINE_ORDERS_VW T4 ON T1.ORDERENTRYID = T4.ORDERENTRYID

LEFT JOIN (SELECT * FROM PROD_DMA_VW.SE2_DOC_TYPE_HISTORY_VW WHERE TYPE2CURRENTFLAG = 1) T5 ON TRIM(LEADING '0' FROM T1.HOLDINGKEY) = T5.CONTRACTNUMBER

LEFT JOIN PROD_DMA_VW.FIRM_DIM_VW T8 ON T1.AGENCYNUMBER = T8.ORIGINALFIRMCODE

LEFT JOIN PROD_USIG_STND_VW.PDCR_DEMOGRAPHICS_VW T9 ON T1.AGENTID = SUBSTR(TRIM(T9.BUSINESS_PARTNER_ID), CHARACTER_LENGTH(TRIM(T9.BUSINESS_PARTNER_ID)) - 5 FOR 6)

LEFT JOIN (SELECT AGREEMENT_ID , MIN(TRANS_DT) AS FIRST_NIGO_DT, MAX(NIGO_RESOLUTION_DATE) AS NIGO_RES_DT

FROM PROD_USIG_STND_VW.AGMT_NIGO_CMN_VW GROUP BY 1) T10 ON T1.AGREEMENTID = T10.AGREEMENT_ID

LEFT JOIN (SELECT DISTINCT T1.AGREEMENT_ID, SUM(TOTAL_DOLLAR_AMOUNT) AS "Deposit Amount"

FROM PROD_USIG_STND_VW.AGMT_PDCR_FIN_TXN_CMN_VW T1

INNER JOIN PROD_USIG_STND_VW.AGMT_CMN_VW T2 ON T1.AGREEMENT_ID = T2.AGREEMENT_ID

WHERE BUSINESS_EVENT_CODE In ('75','76','78','79') AND TRANS_AMOUNT_TYPE = 'TNA' AND TXN_DURATION = 1

AND EXTRACT(YEAR FROM ISSUE_DT) = EXTRACT(YEAR FROM CYCLE_DATE)

GROUP BY 1) T11 ON T1.AGREEMENTID = T11.AGREEMENT_ID

LEFT JOIN PROD_NBR_VW.NB_APPL_VW T12 ON T1.HOLDINGKEY = T12.HLDG_KEY

LEFT JOIN PROD_USIG_CMN_VW.PRODUCT_TRANSLATOR_VW T13 ON T12.PROD_CD = T13.PROD_TYP_CDE

WHERE (PRODUCTNAME LIKE '%MASSMUTUAL%' OR PRODUCTNAME IS NULL)

