SELECT [PolicyNumber]
      ,[OrderType]
      ,[CallerUpdatedAt]
      ,[OverallOrderStatus]
      ,[MCROrderIndicator]
      ,[MCRHitIndicator]
      ,[EHROrderIndicator]
      ,[EHRHitIndicator]
      ,[EHRReviewedIndicator]
      ,[EHRHitType]
      ,[DHPReviewType]
      ,[SubmitDate]
      ,[AmountAtRisk]
      ,[InsuranceAge]
      ,[FirmName]
      ,[Gender]
      ,[InsuredResidentialState]
      ,[UnderwriterName]
      ,[UnderwriterTeam]
      ,[ReplicateIndicator]
  FROM [LifeNewBizReporting].[dbo].[LNBDHPPolicyLevelExtract]