SELECT
	ROOM_UTILIZATION_DT AS 'Room Utilization Date'
	,ROOM_TYP_DESC AS 'Room Type Description'
	,ROOM_DESC AS 'Room Description'
	,ROOM_BOOKING_NBR AS 'Room Booking Count'
	,UTILIZATION_CTG_DESC AS 'Utilization Category'
	,SUM(USED_HRS) AS 'Hours Used'
	,SUM(AVAILABLE_HRS) AS 'Hours Available'
	,SUM(UTILIZATION_PCT) AS 'Utilization Percentage'
FROM
	DMA.dbo.MMLCC_TECH_ROOM_VW
GROUP BY
	ROOM_UTILIZATION_DT
	,ROOM_TYP_DESC
	,ROOM_DESC
	,ROOM_BOOKING_NBR
	,UTILIZATION_CTG_DESC