SELECT	"Event ID"
				, "Event Code"
				, "Event Name"
				, "Event Tier"
				, "Event Category"
				, "Registration Status"
				, "Event Planning Status"
				, "Event Start Date"
				, "Event End Date"
				, "AV Tech Count"
				, "Lead Planner Count"
				, "Event Total Attendees"
				, "Event Total Budget"
				, "Event Total Spend"
				, "Event Total Spend or Budget"
				, "Event Total Negotiated Savings"
				, "Meeting Status Update"
				, "Meeting Status Reason"
FROM	PROD_DMA_VW.CVENT_EVENT_RPT_VW